src/app/(auth)/login/page.tsx
src/app/(auth)/social-register/page.tsx
src/app/layout.tsx
src/app/page.tsx
src/components/common/AuthCard.tsx
src/components/feature/auth/SocialLogin.tsx
src/components/feature/auth/SocialRegister.tsx

소셜 로그인 및 회원 정보 입력 페이지 구현하였습니다.

:sparkles: 소셜 로그인 및 회원 정보 입력 페이지 구현

---

next.config.ts
package-lock.json
package.json
public/mockServiceWorker.js
src/api/axiosInstance.ts
src/app/example/page.tsx
src/app/layout.tsx
src/constants/endPoint.ts
src/hooks/useGetExample.ts
src/mocks/db/db.ts
src/mocks/handlers.ts
src/mocks/http.ts
src/provider/QueryProvider.tsx

Next.js 서버에 MSW(Mock Service Worker) http-middleware를 통합하여 개발 환경의 API 모킹 안정성을 개선했습니다.
- Express 미들웨어를 활용한 MSW 통합
- Next.js 생명주기에 영향을 미치지 않는 서버 사이드 API 모킹 구현
- 개발 및 테스트 환경에서의 일관된 API 모의 처리
- 모든 API 모킹은 개발 환경에서만 적용됨
- 실제 프로덕션 환경에서는 비활성화

:sparkles: Express와 MSW 설치하여 통합 모킹 구현

---

src/app/(protected)/coffee-chat/page.tsx
src/app/layout.tsx
src/components/coffee-chat/CoffeeChatContainer.tsx
src/components/coffee-chat/CoffeeChatHeader.tsx
src/components/coffee-chat/CoffeeChatTabNavigation.tsx
src/components/coffee-chat/FindMentors.tsx
src/components/coffee-chat/MyChatTabNavigation.tsx
src/components/coffee-chat/MyChats.tsx
src/constants/endPoint.ts
src/hooks/coffee-chat/useMentorList.ts
src/mocks/db/db.ts
src/mocks/handlers.ts
src/store/coffee-chat/useCoffeeChatStore.ts

- 커피챗 탭 네비게이션 기능 구현 (커피챗 리스트/보낸요청/받은요청/대화목록)
- 각 탭별 UI 컴포넌트 구현 및 스타일링
- 커피챗 리스트 Mock 서버 연동
- 요청 수락/거절 및 대화 계속하기 버튼 추가 (*기능은 api 구성 완료 후 추가 예정)

:sparkles: 커피챗 탭 네비게이션 및 컨텐츠 구현

---

src/components/mypage/MyPageLayout.tsx
src/components/mypage/MyReviews.tsx
src/components/mypage/ProfileEdit.tsx
src/constants/endPoint.ts
src/hooks/my-page/useGetMyInfo.ts
src/hooks/my-page/useGetMyReviews.ts
src/mocks/db/db.ts
src/mocks/handlers.ts

- 프로필 수정 기능 구현
- 내가 쓴 리뷰 목록 컴포넌트 구현
- 목 데이터 연결 및 관련 훅 구현 완료
#7
텍스트 오버플로우 처리 안 했는데 UI처리가 적절한지 검토 부탁드립니다.
- /mypage 에서 내가 쓴 리뷰 탭 클릭하여 확인

:sparkles: 프로필 수정 및 내가 쓴 리뷰 목록 구현

---

src/app/layout.tsx
src/components/common/Nav.tsx
src/mocks/handlers.ts

:bug: 전체적인 오류 수정

---

src/app/(protected)/mypage/page.tsx
src/components/feature/auth/SocialLogin.tsx

- 마이페이지 경로 오류 수정
- SocialLogin 컴포넌트 오류 수정

:bug: merge 후 오류 수정

---

src/app/(protected)/coffee-chat/page.tsx

:bug: 클라이언트 컴포넌트 변환으로 충돌 해결

---

src/components/common/Header.tsx
src/mocks/db/db.ts
src/mocks/handlers.ts

:bug: PR 머지 후 오류 수정

---

src/components/coffee-chat/CoffeeChatHeader.tsx
src/components/coffee-chat/MentorSignupModal.tsx
src/components/coffee-chat/mentor/ChatRequestModal.tsx
src/components/coffee-chat/mentor/FindMentors.tsx

- 버튼, input, textarea 컴포넌트의 rounded 값 통일
- 버튼 텍스트 변경: "커피챗 등록" → "멘토 등록"

:lipstick: 커피챗 페이지 폼 요소 및 버튼 스타일 일관성 개선

---

src/app/admin/page.tsx

:recycle: 불필요한 Mock worker 삭제

---

src/components/feature/coffee-chat/MentorFormModal.tsx
src/components/feature/coffee-chat/mentor/ChatRequestModal.tsx
src/hooks/coffee-chat/useMentorApplication.ts
src/hooks/coffee-chat/useMentorList.ts
src/types/request.ts
src/types/response.ts

- 커피챗 페이지 서버 연동 후 응답에 따른 데이터 수정

:recycle: 커피챗 페이지 백엔드 서버 연동 후 응답값 수정

---

src/app/(protected)/chat/[roomId]/page.tsx
src/app/(protected)/chat/page.tsx
src/hooks/useWebSocket.ts
src/types/response.ts

- 백엔드 수정에 따른 채팅 목록 응답값 변경
- 타입 구조 변경
- 웹소켓 구독/발행 주소 변경
#33

:wrench: 웹소켓 구독/발행 주소 변경

---

src/app/(protected)/chat/[roomId]/page.tsx
src/components/common/select/FormSelect.tsx
src/components/feature/coffee-chat/mentor/FindMentors.tsx
src/components/feature/mypage/MentorProfile.tsx
src/hooks/coffee-chat/useMentorRegistration.ts
src/hooks/useWebSocket.ts

- 백엔드와 서버 응답에 대한 필드값 통일
- 멘토 정보 호출 시 에러 404에 대한 분기처리
- 웹소켓 토큰 전달 방식 수정, url 에 포함
#33

:recycle: 채팅 백엔드 연동 및 수정

---

src/components/notification/NotificationDropdown.tsx
src/constants/endPoint.ts
src/hooks/notification/useNotificationEffect.ts
src/store/notificationStore.ts
src/types/Notification.ts

1. 클라이언트에서 SSE 연결을 통해 알림을 실시간으로 수신하도록 구현
2. 수신된 알림은 Zustand store에 추가되어 알림 드롭다운에 자동 반영
3. 환경 변수 기반으로 서버 주소를 관리하도록 구성

🚧 SSE 연동 구현

---

src/api/axiosInstance.ts
src/components/common/Header.tsx
src/components/notification/NotificationBell.tsx
src/components/notification/NotificationDropdown.tsx
src/constants/endPoint.ts
src/hooks/main-page/useGetBootcampCategories.ts
src/hooks/notification/useNotificationEffect.ts

1. SSE 관련 엔드포인트 추가
2. 알림 버튼에서 실시간 알림을 받을 수 있도록 수정

🚧 SSE 알림 연동 구현

---

src/components/feature/coffee-chat/mentor/ChatRequestModal.tsx

- DatePicker 컴포넌트는 자체 기본 스타일 시트 추가로 기본 구조와 레이아웃 랜더링 문제 해결

:recycle: DataPicker 자체 기본 스타일 시트 추가로 레이아웃 충돌 해결

---

src/components/common/Header.tsx
src/components/feature/mypage/MyReviews.tsx
src/components/feature/review/ReviewFilterButtons.tsx
src/components/feature/review/ReviewModal.tsx
src/components/feature/review/WriteReviewButton.tsx
src/hooks/admin/useGetCertificationList.ts
src/hooks/main-page/useGetBootcampCategories.ts
src/hooks/notification/useGetNotifications.ts
src/hooks/notification/useInitialNotifications.ts
src/hooks/notification/usePatchNotifications.ts
src/hooks/useSerchSuggestions.ts

1. 소셜 로그인 기능 구현 및 기존 로그인 로직 개선
2. Header에서 로그인된 사용자의 포인트 및 알림 상태 표시
3. 알림 UI 수정: 알림 버튼 클릭 시 모달에서 읽음 상태 업데이트, 헤더에서 읽지 않은 알림 수 표시 제거
4. 직무 목록 조회 시 비로그인 상태에서 오류 수정 및 직무 필터 기능 개선
1. 소셜 로그인과 관련된 코드 수정이 제대로 동작하는지 확인
2. Header에서 포인트와 알림 버튼이 정상적으로 동작하는지 확인
3. 알림 UI에서 상태 변화가 제대로 적용되는지 확인
4. 직무 목록이 비로그인 상태에서도 잘 로딩되는지 확인
1. 소셜 로그인 버튼을 클릭하여 로그인 흐름이 정상적으로 동작하는지 확인
2. 헤더에서 로그인된 사용자 정보(포인트 등) 확인
3. 알림 버튼을 클릭하여 읽지 않은 알림 상태가 헤더에서 제대로 업데이트 되는지 확인
4. 직무 목록이 비로그인 상태에서도 정상적으로 로딩되는지 확인

🚀 배포를 위한 기능 수정

---

src/app/loading.tsx

:recycle: 로딩 파일 추가

---

README.md

📝 Update README.md - troubleshooting

---

README.md

:memo: Update README.md - troubleshooting

---

README.md

📝 : 주요 기능 gif 링크 수정

---

src/mocks/handlers.ts

- Mock server 커피챗 승인/거절 버튼 핸들러 추가

:recycle: 커피챗 승인/거절 버튼 핸들러 추가

---

src/components/feature/coffee-chat/TimeSlotSelectorProps.tsx

- DatePicker 기능은 유지하면서 UI를 아코디언 스타일로 변경
- 선택된 시간 요약 섹션 디자인 통일
- 모든 시간 삭제 기능 추가
- DatePicker 컴포넌트와의 통합이 잘 이루어졌는지 확인
- 시간 선택/삭제 기능이 정상적으로 작동하는지 검토

:recycle: 멘토링 가능 시간 선택 디자인 변경

---

src/components/feature/detail/BootcampDetailClient.tsx
src/components/feature/detail/BootcampDetailInfo.tsx
src/components/feature/detail/BootcampIntro.tsx
src/components/feature/detail/BootcampReview.tsx
src/components/feature/detail/BootcampSchedule.tsx
src/mocks/db/db.ts

1. 상세페이지 상단 제목 타이포 조정
2. 교육기관 정보 카드 스타일 통일
3. 아이콘 색상 및 텍스트 색상 통일
4. 리뷰 섹션 표출 오류 수정
1. 리뷰 카드가 잘 표출되는지 확인
2. 제목 + 구분선 스타일이 반응형에서도 잘 대응되는지 확인
1. 상세페이지 접속 시 상단 제목 및 교육기관 정보 영역 확인
2. 반응형에서도 레이아웃 깨짐 없는지 확인

✨ 상세페이지 UI 개선
